baseurl = "/"
languageCode = "en-us"
title = "芳 | Yang"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
rssLimit = 100

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "简介"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    description = "杨芳的小心思"
    footer = "&copy; [杨芳](https://yang) 2019"
    customJS = [
    "js/fix-toc.js",
    "js/center-img.js",
    "js/right-quote.js",
    "js/no-highlight.js",
    "js/fix-footnote.js",
    "js/math-code.js",
    "js/external-link.js",
    "js/alt-title.js",
    "js/header-link.js"
    ]
    githubContentURL = "https://github.com/john-qu/johnqu.site/edit/master/content/"
    twitterImage = "/images/logo.png"
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
